# Builds and publishes the documentation website to gh-pages branch
name: Build docs

on:
  workflow_dispatch:
  push:
    branches:
      main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          submodules: true

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 8.x

      - name: Install DocLinkChecker
        run: dotnet tool install DocLinkChecker

      # This checks for missing / broken links in the *.md files directly prior to building the website
      - name: Check Documentation Links in Articles
        run: dotnet DocLinkChecker -v -f .github/workflows/DocLinkChecker.config -d articles

      # This checks for missing / broken links in the *.md files directly prior to building the website
      - name: Check Documentation Links in Tutorials
        run: dotnet DocLinkChecker -v -f .github/workflows/DocLinkChecker.config -d tutorials

      - name: Setup DocFX
        run: dotnet tool restore

      - name: Setup Bonsai
        working-directory: .bonsai
        run: .\Setup.ps1

      - name: Build Documentation
        run: .\build.ps1

  check:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # This checks for missing / broken links in the *.html files after building the website.
      # We need to run this step here to check that all auto-generated API pages have valid links too.
      - name: Check HTML Links After Building
        uses: lycheeverse/lychee-action@v1.10.0
        with:
          args: --verbose --no-progress _site/**/*.html
          fail: true

  deploy:
    runs-on: ubuntu-latest
    needs: [build, check]
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4.1.1
        with:
          ref: gh-pages
          path: gh-pages

      - name: Publish to github pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          force_orphan: true
