# Downloads and publishes the documentation website to gh-pages branch
name: Deploy docs

on:
  push:
    branches:
      main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # This will download the artifact from the most recent run of the given workflow.
      # Assumes that the stated workflow was run during a PR check, and then that PR was subsequently approved, triggering this workflow.
      # If there are multiple PRs open, and a new commit is added to a different PR it could lead to a conflict in which artifact is downloaded.
      - name: Download Artifact
        run: |
          repo="${{ github.repository }}"
          workflow="build.yml"
          artifact="_site"
          run_id=`gh run --repo ${repo} list --workflow ${workflow} --json databaseId --jq .[0].databaseId`
          mkdir html
          cd html
          gh run --repo ${repo} download ${run_id} -n ${artifact}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout gh-pages
        uses: actions/checkout@v4.1.1
        with:
          ref: gh-pages
          path: gh-pages

      - name: Publish to github pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          force_orphan: true
